name: Setup
description: Setup tools

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@bfb9fa0b029db830a8c570757cee683df207a6c5 # v2.4.0
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
