name: Setup
description: Setup tools

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
