name: Setup
description: Setup tools

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
